version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.6.5-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: rasa-action:v1
    expose:
      - 5005
