version: '3.0'
services:
  rasa:
    container_name: "rasa_server"
    user: root
    build:
      context: .
    volumes:
      - "./:/app"
    ports:
      - "5005:5005"

  action_server:
    image: rasa/rasa-sdk:latest
    restart: always
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055
